import type { RepoProfile, GeneratedFile } from "@/lib/types";
import type { ProseBlocks } from "@/lib/generate/prose";

function list(items: string[], fallback = "—"): string {
  return items.length ? items.join(", ") : fallback;
}

function bullets(items: string[]): string {
  return items.map((i) => `- ${i}`).join("\n");
}

function commandsBlock(profile: RepoProfile): string {
  const s = profile.scripts;
  const lines: string[] = [];
  if (s.install) lines.push(s.install);
  if (s.dev) lines.push(s.dev);
  if (s.lint) lines.push(s.lint);
  if (s.typecheck) lines.push(s.typecheck);
  if (s.test) lines.push(s.test);
  if (s.build) lines.push(s.build);
  if (lines.length === 0) lines.push("# No package.json scripts detected");
  return lines.join("\n");
}

function stackSummary(profile: RepoProfile): string {
  const parts: string[] = [];
  if (profile.frameworks.length) parts.push(profile.frameworks.join(" + "));
  if (profile.languages.length) parts.push(profile.languages.slice(0, 3).join("/"));
  if (profile.packageManager !== "unknown") parts.push(`${profile.packageManager}`);
  return parts.join(" · ") || "Unknown stack";
}

function defaultSummary(profile: RepoProfile): string {
  if (profile.description) return profile.description;
  const fw = profile.frameworks[0] ?? profile.primaryLanguage ?? "software";
  return `${profile.repo} is a ${fw} project.`;
}

function defaultArchitecture(profile: RepoProfile): string {
  const segs: string[] = [];
  if (profile.frameworks.length) {
    segs.push(`Built with ${list(profile.frameworks)}.`);
  }
  if (profile.hasFrontend && profile.frontendDirs.length) {
    segs.push(`Frontend code lives in ${list(profile.frontendDirs)}.`);
  }
  if (profile.hasBackend && profile.backendDirs.length) {
    segs.push(`Server/API code lives in ${list(profile.backendDirs)}.`);
  }
  if (profile.database.length) {
    segs.push(`Data layer uses ${list(profile.database)}.`);
  }
  if (profile.monorepo) {
    segs.push("This is a monorepo with multiple workspaces.");
  }
  return segs.join(" ") || "See the directory layout for how the project is organized.";
}

function defaultConventions(profile: RepoProfile): string[] {
  const c: string[] = [];
  if (profile.packageManager !== "unknown") {
    c.push(`Use \`${profile.packageManager}\` as the package manager.`);
  }
  if (profile.languages.includes("TypeScript")) {
    c.push("Write TypeScript with explicit types for public APIs; avoid `any`.");
  }
  if (profile.styling.includes("Tailwind CSS")) {
    c.push("Style with Tailwind utility classes; avoid ad-hoc inline styles.");
  }
  if (profile.uiLibraries.includes("shadcn/ui")) {
    c.push("Reuse existing shadcn/ui components instead of creating new primitives.");
  }
  if (profile.testing.length) {
    c.push(`Add/update tests using ${list(profile.testing)} when changing behavior.`);
  }
  c.push("Match the existing file structure and naming conventions.");
  c.push("Keep changes focused; do not reformat unrelated code.");
  return c;
}

function directoryBlock(profile: RepoProfile): string {
  if (!profile.notableDirs.length) return "";
  return profile.notableDirs.map((d) => `- \`${d}/\``).join("\n");
}

// ---------------------------------------------------------------------------
// AGENTS.md
// ---------------------------------------------------------------------------
export function buildAgentsMd(profile: RepoProfile, prose: ProseBlocks): string {
  const summary = prose.summary || defaultSummary(profile);
  const architecture = prose.architecture || defaultArchitecture(profile);
  const conventions = prose.conventions?.length ? prose.conventions : defaultConventions(profile);
  const dirs = directoryBlock(profile);

  return `# AGENTS.md

> Operating instructions for AI coding agents (Claude, Cursor, Copilot, Codex, Devin, Windsurf). Generated by [GitVane](https://github.com/Erfan-FK/GitVane).

## What this repo is

${summary}

- **Stack:** ${stackSummary(profile)}
- **Primary language:** ${profile.primaryLanguage ?? list(profile.languages)}
- **Package manager:** ${profile.packageManager}
${profile.frameworks.length ? `- **Frameworks:** ${list(profile.frameworks)}` : ""}
${profile.database.length ? `- **Data layer:** ${list(profile.database)}` : ""}
${profile.testing.length ? `- **Testing:** ${list(profile.testing)}` : ""}

## Architecture

${architecture}
${dirs ? `\n### Key directories\n\n${dirs}\n` : ""}
## Commands

Always use these exact commands. Do not guess.

\`\`\`bash
${commandsBlock(profile)}
\`\`\`

See \`docs/validation.md\` for the full validation runbook.

## Conventions

${bullets(conventions)}

## What NOT to do

${bullets(profile.riskNotes)}

See \`docs/failure-modes.md\` for the complete list of risky areas.

## Before you finish

- Run the validation commands above and make sure they pass.
- Keep the diff minimal and consistent with the surrounding code.
- Update documentation when you change behavior.
`;
}

// ---------------------------------------------------------------------------
// CLAUDE.md (points at AGENTS.md to stay in sync)
// ---------------------------------------------------------------------------
export function buildClaudeMd(profile: RepoProfile): string {
  return `# CLAUDE.md

This project's agent instructions live in [\`AGENTS.md\`](./AGENTS.md). Claude Code reads this file — treat \`AGENTS.md\` as the source of truth.

## Quick reference

- **Stack:** ${stackSummary(profile)}
- **Install:** \`${profile.scripts.install ?? "n/a"}\`
- **Dev:** \`${profile.scripts.dev ?? "n/a"}\`
- **Validate:** see \`docs/validation.md\`

Read \`AGENTS.md\` fully before making changes.
`;
}

// ---------------------------------------------------------------------------
// .github/copilot-instructions.md
// ---------------------------------------------------------------------------
export function buildCopilotInstructions(profile: RepoProfile, prose: ProseBlocks): string {
  const conventions = prose.conventions?.length ? prose.conventions : defaultConventions(profile);
  return `# GitHub Copilot Instructions

${prose.summary || defaultSummary(profile)}

## Stack

- ${stackSummary(profile)}
- Package manager: **${profile.packageManager}** — use it for all dependency operations.

## Coding conventions

${bullets(conventions)}

## Checks to run

Before suggesting that work is complete, ensure these pass:

\`\`\`bash
${commandsBlock(profile)}
\`\`\`

## Guardrails

${bullets(profile.riskNotes)}
`;
}

// ---------------------------------------------------------------------------
// .cursor/rules/project.mdc
// ---------------------------------------------------------------------------
export function buildCursorRules(profile: RepoProfile, prose: ProseBlocks): string {
  const conventions = prose.conventions?.length ? prose.conventions : defaultConventions(profile);
  return `---
description: Project conventions and guardrails for ${profile.owner}/${profile.repo}
globs:
alwaysApply: true
---

# ${profile.repo} — Cursor Rules

${prose.summary || defaultSummary(profile)}

## Stack
- ${stackSummary(profile)}
- Package manager: ${profile.packageManager}

## Conventions
${bullets(conventions)}

## Validation
Run before considering a task done:
\`\`\`bash
${commandsBlock(profile)}
\`\`\`

## Boundaries
${bullets(profile.riskNotes)}

${
  profile.hasFrontend && profile.hasBackend
    ? "## Frontend / backend\n- Keep client and server concerns separate. Do not import server-only modules into client components."
    : ""
}
`;
}

// ---------------------------------------------------------------------------
// .windsurf/rules/project.md
// ---------------------------------------------------------------------------
export function buildWindsurfRules(profile: RepoProfile, prose: ProseBlocks): string {
  const conventions = prose.conventions?.length ? prose.conventions : defaultConventions(profile);
  return `---
trigger: always_on
---

# ${profile.repo} — Windsurf Rules

${prose.summary || defaultSummary(profile)}

## Stack
- ${stackSummary(profile)}
- Package manager: **${profile.packageManager}**

## Conventions
${bullets(conventions)}

## Validation commands
\`\`\`bash
${commandsBlock(profile)}
\`\`\`

## Do not
${bullets(profile.riskNotes)}
`;
}

// ---------------------------------------------------------------------------
// docs/validation.md
// ---------------------------------------------------------------------------
export function buildValidationMd(profile: RepoProfile): string {
  const s = profile.scripts;
  const rows: Array<[string, string | null]> = [
    ["Install", s.install],
    ["Dev server", s.dev],
    ["Lint", s.lint],
    ["Typecheck", s.typecheck],
    ["Test", s.test],
    ["Build", s.build],
    ["Format", s.format],
    ["Start", s.start],
  ];
  const table = rows
    .map(([label, cmd]) => `| ${label} | ${cmd ? `\`${cmd}\`` : "_not detected_"} |`)
    .join("\n");

  const ordered = [s.install, s.lint, s.typecheck, s.test, s.build].filter(Boolean) as string[];

  return `# Validation Runbook

How to check your work in this repo. Agents often guess commands incorrectly — these are the **exact** commands detected from \`package.json\` and the lockfile.

## Commands

| Step | Command |
| --- | --- |
${table}

## Recommended order

\`\`\`bash
${ordered.length ? ordered.join("\n") : "# No scripts detected in package.json"}
\`\`\`

## Notes

- Package manager: **${profile.packageManager}**. ${
    profile.packageManager !== "unknown"
      ? `Do not use other package managers.`
      : `No lockfile detected — confirm the intended package manager before installing.`
  }
${profile.allScripts.length ? `\n### All package.json scripts\n\n${profile.allScripts.map((sc) => `- \`${sc.name}\`: \`${sc.raw}\``).join("\n")}` : ""}
`;
}

// ---------------------------------------------------------------------------
// docs/failure-modes.md
// ---------------------------------------------------------------------------
export function buildFailureModesMd(profile: RepoProfile, prose: ProseBlocks): string {
  const risks = [...profile.riskNotes, ...(prose.extraRisks ?? [])];
  return `# Failure Modes

A "be careful" guide: risky areas, common mistakes, and files agents should not touch.

## Do not touch

${bullets(risks)}

## Generated / build output

Do not hand-edit generated files. Regenerate them instead.
${profile.ormFiles.length ? `\n- ORM schema/config: ${list(profile.ormFiles)} (edit schema, then regenerate)` : ""}
- Build output: \`dist/\`, \`build/\`, \`.next/\`, \`out/\`, \`coverage/\`

${
  profile.database.length
    ? `## Database\n\n- Uses ${list(profile.database)}. Do not modify already-applied migrations. Create new migrations for schema changes.\n`
    : ""
}${
    profile.envVars.length
      ? `## Environment\n\n- Required env vars (see \`.env.example\`): ${profile.envVars.map((v) => `\`${v}\``).join(", ")}. Never commit real secrets.\n`
      : ""
  }`;
}

// ---------------------------------------------------------------------------
// docs/design-system.md (frontend only)
// ---------------------------------------------------------------------------
export function buildDesignSystemMd(profile: RepoProfile, prose: ProseBlocks): string {
  const notes = prose.designNotes;
  return `# Design System

How UI should look and behave in this repo, so generated UI matches the existing app.

## Styling

- Styling approach: ${list(profile.styling, "not detected")}
${profile.uiLibraries.length ? `- UI libraries: ${list(profile.uiLibraries)}` : ""}
${profile.frontendDirs.length ? `- Components live in: ${list(profile.frontendDirs)}` : ""}

${notes ? `## Conventions\n\n${notes}\n` : ""}
## Rules for new UI

- Reuse existing components before creating new ones.
${profile.styling.includes("Tailwind CSS") ? "- Use Tailwind utility classes and the existing theme tokens; do not introduce arbitrary one-off colors." : ""}
${profile.uiLibraries.includes("shadcn/ui") ? "- Follow shadcn/ui patterns; compose primitives rather than restyling them." : ""}
- Reuse existing loading, empty, and error states.
- Keep spacing, radius, and typography consistent with current components.
`;
}

// ---------------------------------------------------------------------------
// docs/api-map.md (backend only)
// ---------------------------------------------------------------------------
export function buildApiMapMd(profile: RepoProfile, prose: ProseBlocks): string {
  const notes = prose.apiNotes;
  const routes = profile.apiRoutes.length
    ? profile.apiRoutes.map((r) => `- \`${r}\``).join("\n")
    : "_No file-based API routes detected. See server/controller directories below._";

  return `# API Map

How the backend is organized, so agents avoid breaking server logic.

## Structure

${profile.backendDirs.length ? `- Server/API directories: ${list(profile.backendDirs)}` : "- No standard server directories detected."}
${profile.frameworks.filter((f) => ["Express", "Fastify", "NestJS", "Hono", "Koa", "Next.js"].includes(f)).length ? `- Framework: ${list(profile.frameworks.filter((f) => ["Express", "Fastify", "NestJS", "Hono", "Koa", "Next.js"].includes(f)))}` : ""}
${profile.database.length ? `- Data layer: ${list(profile.database)}` : ""}

## Routes / handlers

${routes}

${notes ? `## Conventions\n\n${notes}\n` : ""}
## Rules

- Preserve existing response shapes and status codes; clients depend on them.
- Validate and sanitize all request input.
- Do not bypass authentication/authorization checks.
${profile.database.length ? "- Access the database through the existing data layer; do not write ad-hoc queries that skip it." : ""}
`;
}

// ---------------------------------------------------------------------------
// llms.txt (root LLM index — see llmstxt.org)
// ---------------------------------------------------------------------------
export function buildLlmsTxt(profile: RepoProfile, prose: ProseBlocks): string {
  const summary = prose.summary || defaultSummary(profile);
  const repoUrl = `https://github.com/${profile.owner}/${profile.repo}`;

  const docLinks: string[] = [
    `- [AGENTS.md](${repoUrl}/blob/${profile.defaultBranch}/AGENTS.md): Operating instructions for AI coding agents.`,
    `- [Validation runbook](${repoUrl}/blob/${profile.defaultBranch}/docs/validation.md): Exact install, lint, test, and build commands.`,
    `- [Failure modes](${repoUrl}/blob/${profile.defaultBranch}/docs/failure-modes.md): Risky areas and files not to touch.`,
  ];
  if (profile.hasFrontend) {
    docLinks.push(
      `- [Design system](${repoUrl}/blob/${profile.defaultBranch}/docs/design-system.md): UI and styling conventions.`,
    );
  }
  if (profile.hasBackend) {
    docLinks.push(
      `- [API map](${repoUrl}/blob/${profile.defaultBranch}/docs/api-map.md): Routes, handlers, and server conventions.`,
    );
  }

  const dirs = profile.notableDirs.length
    ? profile.notableDirs.map((d) => `- \`${d}/\``).join("\n")
    : "- See the repository root for layout.";

  return `# ${profile.owner}/${profile.repo}

> ${summary}

- **Stack:** ${stackSummary(profile)}
- **Primary language:** ${profile.primaryLanguage ?? list(profile.languages)}
- **Package manager:** ${profile.packageManager}
- **Repository:** ${repoUrl}

## Docs

${docLinks.join("\n")}

## Key directories

${dirs}

## Commands

\`\`\`bash
${commandsBlock(profile)}
\`\`\`

## Notes

This file is an [llms.txt](https://llmstxt.org) index generated by GitVane. Read \`AGENTS.md\` for the full operating instructions before making changes.
`;
}

// ---------------------------------------------------------------------------
// Detection helpers for specialized files
// ---------------------------------------------------------------------------
const AUTH_ENV_RE =
  /(AUTH|CLERK|NEXTAUTH|JWT|SESSION|SUPABASE|OAUTH|COGNITO|FIREBASE|KINDE|AUTH0|MAGIC|TOKEN|SECRET_KEY)/i;

export function hasAuthSignals(profile: RepoProfile): boolean {
  if (profile.database.some((d) => /supabase|firebase/i.test(d))) return true;
  if (profile.frameworks.some((f) => /next-auth|clerk|auth0|lucia|kinde/i.test(f))) return true;
  return profile.envVars.some((v) => AUTH_ENV_RE.test(v));
}

/** Turn a list of directories into a single Copilot `applyTo` glob string. */
function applyToGlob(dirs: string[], fallback: string): string {
  const globs = dirs.length
    ? dirs.map((d) => `${d.replace(/\/$/, "")}/**`)
    : [fallback];
  return globs.join(", ");
}

// ---------------------------------------------------------------------------
// .github/instructions/frontend.instructions.md (path-scoped Copilot rules)
// ---------------------------------------------------------------------------
export function buildFrontendInstructions(profile: RepoProfile): string {
  const styleBullets: string[] = [];
  if (profile.styling.includes("Tailwind CSS"))
    styleBullets.push("Use Tailwind utility classes and existing theme tokens; avoid one-off inline styles or arbitrary colors.");
  if (profile.uiLibraries.includes("shadcn/ui"))
    styleBullets.push("Compose existing shadcn/ui primitives instead of restyling or hand-rolling them.");
  if (profile.uiLibraries.length)
    styleBullets.push(`Reuse the project's UI libraries (${list(profile.uiLibraries)}) rather than adding new ones.`);
  styleBullets.push("Reuse existing components, and existing loading / empty / error states.");
  styleBullets.push("Keep spacing, radius, and typography consistent with current components.");
  if (profile.hasBackend)
    styleBullets.push("Never import server-only modules into client components.");

  return `---
applyTo: "${applyToGlob(profile.frontendDirs, "src/**")}"
---

# Frontend instructions

Path-scoped guidance for UI code in ${profile.owner}/${profile.repo}. These rules apply only to the frontend directories above.

## Stack
- ${stackSummary(profile)}
- Styling: ${list(profile.styling, "not detected")}
${profile.uiLibraries.length ? `- UI libraries: ${list(profile.uiLibraries)}` : ""}
${profile.frontendDirs.length ? `- Frontend lives in: ${profile.frontendDirs.map((d) => `\`${d}/\``).join(", ")}` : ""}

## Rules
${bullets(styleBullets)}

See \`docs/design-system.md\` for the full design system.
`;
}

// ---------------------------------------------------------------------------
// .github/instructions/backend.instructions.md (path-scoped Copilot rules)
// ---------------------------------------------------------------------------
export function buildBackendInstructions(profile: RepoProfile): string {
  const rules: string[] = [
    "Validate and sanitize all request input before using it.",
    "Preserve existing response shapes and status codes — clients depend on them.",
    "Do not bypass authentication or authorization checks.",
  ];
  if (profile.database.length)
    rules.push(`Access data only through the existing data layer (${list(profile.database)}); do not write ad-hoc queries that skip it.`);
  rules.push("Handle errors explicitly and return consistent error responses.");
  rules.push("Keep business logic out of route handlers where the codebase already separates it.");

  return `---
applyTo: "${applyToGlob(profile.backendDirs, "src/**")}"
---

# Backend instructions

Path-scoped guidance for server/API code in ${profile.owner}/${profile.repo}. These rules apply only to the backend directories above.

## Stack
- ${stackSummary(profile)}
${profile.backendDirs.length ? `- Server/API lives in: ${profile.backendDirs.map((d) => `\`${d}/\``).join(", ")}` : ""}
${profile.database.length ? `- Data layer: ${list(profile.database)}` : ""}

## Rules
${bullets(rules)}

See \`docs/api-map.md\` for the full route map${hasAuthSignals(profile) ? " and `docs/auth-flow.md` for authentication" : ""}.
`;
}

// ---------------------------------------------------------------------------
// docs/auth-flow.md
// ---------------------------------------------------------------------------
export function buildAuthFlowMd(profile: RepoProfile): string {
  const provider =
    profile.frameworks.find((f) => /next-auth|clerk|auth0|lucia|kinde/i.test(f)) ??
    (profile.database.find((d) => /supabase|firebase/i.test(d)) ?? null);
  const authEnv = profile.envVars.filter((v) => AUTH_ENV_RE.test(v));

  return `# Auth Flow

How authentication works in ${profile.owner}/${profile.repo}, so agents don't bypass it or break protected routes.

## Provider
${provider ? `- Detected auth provider: **${provider}**.` : "- No specific auth library detected — authentication appears custom. Read the middleware and server entry points before changing anything."}
${authEnv.length ? `- Auth-related env vars: ${authEnv.map((v) => `\`${v}\``).join(", ")}.` : ""}
${profile.backendDirs.length ? `- Server code lives in ${profile.backendDirs.map((d) => `\`${d}/\``).join(", ")}.` : ""}

## Rules
- Never remove or weaken authentication or authorization checks.
- Treat session/token handling as security-critical; do not log secrets or tokens.
- New protected routes must enforce the same auth checks as existing ones.
- Read how sessions are created and validated before modifying login, logout, or middleware.
${authEnv.length ? "- Required auth env vars must be set in every environment; never commit real values." : ""}

## Before you finish
- Confirm protected routes still reject unauthenticated requests.
- Confirm sign-in / sign-out still work end to end.
`;
}

// ---------------------------------------------------------------------------
// docs/database.md
// ---------------------------------------------------------------------------
export function buildDatabaseMd(profile: RepoProfile): string {
  return `# Database Guide

How data is stored and accessed in ${profile.owner}/${profile.repo}.

## Stack
- Data layer: ${list(profile.database)}
${profile.ormFiles.length ? `- Schema / config files: ${profile.ormFiles.map((f) => `\`${f}\``).join(", ")}` : ""}

## Rules
- Access the database only through the existing data layer; do not introduce a second client or ad-hoc queries.
- Do **not** edit migrations that have already been applied. Create a new migration for any schema change.
${profile.ormFiles.length ? "- Edit the schema file, then regenerate types/client — do not hand-edit generated output." : ""}
- Keep queries parameterized; never build SQL by string concatenation.
- Consider indexes and N+1 queries when adding data access in hot paths.

## Before you finish
- Run any migration/codegen step for your data layer.
- Make sure the app still boots and connects with the documented env vars.
`;
}

// ---------------------------------------------------------------------------
// docs/env-vars.md
// ---------------------------------------------------------------------------
export function buildEnvVarsMd(profile: RepoProfile): string {
  const rows = profile.envVars.map((v) => {
    const sensitive = /(SECRET|TOKEN|KEY|PASSWORD|PRIVATE|DSN|URL)/i.test(v);
    const note = sensitive ? "Secret — keep out of version control" : "Configuration";
    return `| \`${v}\` | ${note} |`;
  });

  return `# Environment Variables

Environment variables detected in ${profile.owner}/${profile.repo} (from \`.env.example\` and config). Use these to configure and run the app.

## Variables

| Variable | Notes |
| --- | --- |
${rows.join("\n")}

## Rules
- Copy \`.env.example\` to \`.env.local\` (or your environment) and fill in real values.
- Never commit real secrets. Add new variables to \`.env.example\` with a placeholder.
- Read variables through the existing config layer rather than \`process.env\` scattered across the codebase.
- Treat any variable containing a secret/token/key as sensitive.
`;
}

// ---------------------------------------------------------------------------
// Orchestrate all template files
// ---------------------------------------------------------------------------
export function buildAllFiles(profile: RepoProfile, prose: ProseBlocks): GeneratedFile[] {
  const enriched: GeneratedFile["source"] =
    Object.keys(prose).length > 0 ? "llm-verified" : "template";

  const files: GeneratedFile[] = [
    { path: "AGENTS.md", content: buildAgentsMd(profile, prose), language: "markdown", source: enriched, tier: "free" },
    { path: "llms.txt", content: buildLlmsTxt(profile, prose), language: "markdown", source: enriched, tier: "free" },
    { path: "CLAUDE.md", content: buildClaudeMd(profile), language: "markdown", source: "template", tier: "free" },
    {
      path: ".github/copilot-instructions.md",
      content: buildCopilotInstructions(profile, prose),
      language: "markdown",
      source: enriched,
      tier: "free",
    },
    {
      path: ".cursor/rules/project.mdc",
      content: buildCursorRules(profile, prose),
      language: "markdown",
      source: enriched,
      tier: "free",
    },
    {
      path: ".windsurf/rules/project.md",
      content: buildWindsurfRules(profile, prose),
      language: "markdown",
      source: enriched,
      tier: "free",
    },
    {
      path: "docs/validation.md",
      content: buildValidationMd(profile),
      language: "markdown",
      source: "template",
      tier: "free",
    },
    {
      path: "docs/failure-modes.md",
      content: buildFailureModesMd(profile, prose),
      language: "markdown",
      source: "template",
      tier: "free",
    },
  ];

  if (profile.hasFrontend) {
    files.push({
      path: "docs/design-system.md",
      content: buildDesignSystemMd(profile, prose),
      language: "markdown",
      source: prose.designNotes ? "llm-verified" : "template",
      tier: "premium",
    });
  }
  if (profile.hasBackend) {
    files.push({
      path: "docs/api-map.md",
      content: buildApiMapMd(profile, prose),
      language: "markdown",
      source: prose.apiNotes ? "llm-verified" : "template",
      tier: "premium",
    });
  }

  // Path-scoped Copilot instructions.
  if (profile.hasFrontend) {
    files.push({
      path: ".github/instructions/frontend.instructions.md",
      content: buildFrontendInstructions(profile),
      language: "markdown",
      source: "template",
      tier: "premium",
    });
  }
  if (profile.hasBackend) {
    files.push({
      path: ".github/instructions/backend.instructions.md",
      content: buildBackendInstructions(profile),
      language: "markdown",
      source: "template",
      tier: "premium",
    });
  }

  // Auth flow when authentication signals are detected.
  if (hasAuthSignals(profile)) {
    files.push({
      path: "docs/auth-flow.md",
      content: buildAuthFlowMd(profile),
      language: "markdown",
      source: "template",
      tier: "premium",
    });
  }

  // Database guide when a data layer is detected.
  if (profile.database.length) {
    files.push({
      path: "docs/database.md",
      content: buildDatabaseMd(profile),
      language: "markdown",
      source: "template",
      tier: "premium",
    });
  }

  // Environment variables when any are detected.
  if (profile.envVars.length) {
    files.push({
      path: "docs/env-vars.md",
      content: buildEnvVarsMd(profile),
      language: "markdown",
      source: "template",
      tier: "premium",
    });
  }

  return files;
}
